services:
  enkel-ao:
    build: .
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - LOCATION_DB_PATH=/shared/locations.db
    volumes:
      - ao-data:/data
      - shared-locations:/shared
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dozzle:
    image: amir20/dozzle:latest
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./users.yml:/data/users.yml
    environment:
      DOZZLE_NO_ANALYTICS: "true"
      DOZZLE_AUTH_PROVIDER: "simple"
      DOZZLE_TAILSIZE: "5000"

volumes:
  ao-data:
  shared-locations:
    external: true
